import Link from 'next/link';
import { BudgetTable } from '@/components/BudgetTable';
import { KpiCard } from '@/components/KpiCard';
import { Nav } from '@/components/Nav';
import { requireBudgetAccess } from '@/lib/access';
import { loadBudgetData } from '@/lib/budget-data';
import { buildMonthlySummary, yearTotals } from '@/lib/calculations';
import { formatMoney } from '@/lib/format';
export default async function BudgetPage({ params }: { params: Promise<{ budgetYearId: string }> }) { const { budgetYearId } = await params; await requireBudgetAccess(budgetYearId); const { budgetYear, groups, entries } = await loadBudgetData(budgetYearId); const summary=buildMonthlySummary({entries, beginningSpendingBalance:Number(budgetYear.beginningSpendingBalance), beginningSavingsBalance:Number(budgetYear.beginningSavingsBalance)}); const totals=yearTotals(summary); return <><Nav budgetYearId={budgetYearId}/><main className="mx-auto max-w-7xl px-6 py-8"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><h1 className="text-3xl font-semibold tracking-tight">Budget {budgetYear.year}</h1><p className="mt-2 text-slate-500">Các ô Jan–Dec tự lưu khi rời khỏi ô.</p></div><div className="flex gap-2"><Link href={`/api/export/${budgetYearId}`} className="rounded-lg border bg-white px-4 py-2 text-sm font-medium">Export Excel</Link><Link href={`/reports/${budgetYearId}`} className="rounded-lg bg-slate-950 px-4 py-2 text-sm font-medium text-white">Reports</Link></div></div><section className="mt-8 grid gap-4 md:grid-cols-3 lg:grid-cols-6"><KpiCard label="Income" value={formatMoney(totals.income,budgetYear.currency)}/><KpiCard label="Expenses" value={formatMoney(totals.expenses,budgetYear.currency)}/><KpiCard label="Savings" value={formatMoney(totals.savings,budgetYear.currency)}/><KpiCard label="Net" value={formatMoney(totals.net,budgetYear.currency)}/><KpiCard label="Spending Balance" value={formatMoney(totals.spendingBalance,budgetYear.currency)}/><KpiCard label="Savings Balance" value={formatMoney(totals.savingsBalance,budgetYear.currency)}/></section><section className="mt-8"><BudgetTable budgetYearId={budgetYearId} groups={groups} entries={entries} currency={budgetYear.currency}/></section></main></> }
