import { GroupType } from '@prisma/client';
import { BalanceChart, ExpensePie, IncomeExpenseChart } from '@/components/Charts';
import { KpiCard } from '@/components/KpiCard';
import { Nav } from '@/components/Nav';
import { requireBudgetAccess } from '@/lib/access';
import { loadBudgetData } from '@/lib/budget-data';
import { buildMonthlySummary, groupMonthlyTotal, yearTotals } from '@/lib/calculations';
import { formatMoney } from '@/lib/format';
import { months } from '@/lib/months';
export default async function ReportsPage({ params }: { params: Promise<{ budgetYearId: string }> }) { const { budgetYearId } = await params; await requireBudgetAccess(budgetYearId); const { budgetYear, groups, entries } = await loadBudgetData(budgetYearId); const summary=buildMonthlySummary({entries, beginningSpendingBalance:Number(budgetYear.beginningSpendingBalance), beginningSavingsBalance:Number(budgetYear.beginningSavingsBalance)}); const totals=yearTotals(summary); const chartData=summary.map(s=>({...s,month:months[s.month-1].label})); const expenseGroups=groups.filter(g=>g.type===GroupType.EXPENSE).map(g=>({name:g.name,value:months.reduce((sum,m)=>sum+groupMonthlyTotal(entries,g.id,m.index),0)})).filter(g=>g.value>0).sort((a,b)=>b.value-a.value); const top=expenseGroups[0]; return <><Nav budgetYearId={budgetYearId}/><main className="mx-auto max-w-7xl px-6 py-8"><h1 className="text-3xl font-semibold tracking-tight">Reports {budgetYear.year}</h1><section className="mt-8 grid gap-4 md:grid-cols-4"><KpiCard label="Total Income" value={formatMoney(totals.income,budgetYear.currency)}/><KpiCard label="Total Expenses" value={formatMoney(totals.expenses,budgetYear.currency)}/><KpiCard label="Total Savings" value={formatMoney(totals.savings,budgetYear.currency)}/><KpiCard label="Top Expense Group" value={top?.name ?? 'N/A'} hint={top ? formatMoney(top.value,budgetYear.currency):undefined}/></section><section className="mt-8 grid gap-6 lg:grid-cols-2"><IncomeExpenseChart data={chartData}/><BalanceChart data={chartData}/><ExpensePie data={expenseGroups}/><div className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-semibold">Expense ranking</h3><div className="mt-4 divide-y">{expenseGroups.map(i=><div key={i.name} className="flex items-center justify-between py-3 text-sm"><span>{i.name}</span><span className="font-medium">{formatMoney(i.value,budgetYear.currency)}</span></div>)}</div></div></section></main></> }
