import type React from 'react';
import { CategoryGroup, GroupType } from '@prisma/client';
import { AmountCell } from '@/components/AmountCell';
import { categoryYearTotal, groupMonthlyTotal, type FlatBudgetEntry } from '@/lib/calculations';
import { formatMoney, percent } from '@/lib/format';
import { months } from '@/lib/months';
type GroupWithCategories = CategoryGroup & { categories: { id: string; name: string; sortOrder: number; archived: boolean }[] };
export function BudgetTable({ budgetYearId, groups, entries, currency }: { budgetYearId:string; groups:GroupWithCategories[]; entries:FlatBudgetEntry[]; currency:string }) {
  const expenseByMonth = months.map(m => entries.filter(e => e.month === m.index && e.groupType === GroupType.EXPENSE).reduce((s,e)=>s+e.amount,0));
  return <div className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="overflow-auto"><table className="min-w-[1280px] w-full border-collapse text-sm"><thead className="sticky top-0 z-10 bg-slate-100 text-slate-700"><tr><th className="w-64 border-b px-4 py-3 text-left font-semibold">Category</th>{months.map(m=><th key={m.index} className="border-b px-2 py-3 text-right font-semibold">{m.label}</th>)}<th className="border-b px-3 py-3 text-right font-semibold">Total</th><th className="border-b px-3 py-3 text-right font-semibold">Average</th></tr></thead><tbody>{groups.map(group=>{const groupTotal=months.reduce((s,m)=>s+groupMonthlyTotal(entries,group.id,m.index),0); return <FragmentLike key={group.id}><tr className="bg-slate-900 text-white"><td className="px-4 py-2 font-semibold">{group.name}</td>{months.map(m=><td key={m.index} className="px-2 py-2 text-right font-semibold">{formatMoney(groupMonthlyTotal(entries,group.id,m.index),currency)}</td>)}<td className="px-3 py-2 text-right font-semibold">{formatMoney(groupTotal,currency)}</td><td className="px-3 py-2 text-right font-semibold">{formatMoney(groupTotal/12,currency)}</td></tr>{group.categories.filter(c=>!c.archived).map(category=>{const total=categoryYearTotal(entries,category.id); return <tr key={category.id} className="border-b hover:bg-slate-50"><td className="px-4 py-2 text-slate-700">{category.name}</td>{months.map(m=><td key={m.index} className="px-1 py-1 text-right"><AmountCell budgetYearId={budgetYearId} categoryId={category.id} month={m.index} value={entries.find(e=>e.categoryId===category.id && e.month===m.index)?.amount ?? 0}/></td>)}<td className="px-3 py-2 text-right font-medium">{formatMoney(total,currency)}</td><td className="px-3 py-2 text-right text-slate-600">{formatMoney(total/12,currency)}</td></tr>})}{group.type===GroupType.EXPENSE?<tr className="border-b bg-slate-50 text-xs text-slate-500"><td className="px-4 py-2">% of Total Expenses</td>{months.map((m,idx)=>{const denom=expenseByMonth[idx]; const ratio=denom===0?0:groupMonthlyTotal(entries,group.id,m.index)/denom; return <td key={m.index} className="px-2 py-2 text-right">{percent(ratio)}</td>})}<td colSpan={2}/></tr>:null}</FragmentLike>})}</tbody></table></div></div>
}
function FragmentLike({children}:{children:React.ReactNode}) { return <>{children}</>; }
